# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail_Introduce', models.CharField(max_length=50)),
                ('Detail_Comment', models.CharField(max_length=50)),
                ('Detail_love', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BALANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance_SumNum', models.IntegerField(max_length=10)),
                ('Balance_SumPrice', models.FloatField()),
                ('Balance_PayPrice', models.FloatField()),
                ('address_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_CountNum', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GOODS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goods_Name', models.CharField(max_length=20)),
                ('Goods_Type', models.CharField(max_length=20)),
                ('Goods_Price', models.FloatField()),
                ('Goods_Units', models.CharField(max_length=20)),
                ('Goods_Content', models.CharField(max_length=50)),
                ('Goods_num', models.IntegerField(max_length=10)),
                ('Goods_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ORDERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders_CreateTime', models.DateTimeField()),
                ('Orders_Num', models.IntegerField(max_length=10)),
                ('Orders_Pay', models.BooleanField(default=False)),
                ('Orders_SumPrice', models.FloatField()),
                ('balance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.BALANCE')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.CAR')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.GOODS'),
        ),
        migrations.AddField(
            model_name='balance',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.CAR'),
        ),
    ]
